# Use an image that already has Python pre-installed
FROM python:3.11-slim-bookworm

# Install ONLY Java cleanly and quickly
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-17-jre-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set Environment Variables for Java (Required for PySpark)
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$PATH:$JAVA_HOME/bin

# Install PySpark
RUN pip3 install --no-cache-dir pyspark

# Set the working directory inside the container
WORKDIR /app

# Copy the application code and data into the container
COPY app.py /app/app.py
COPY data/ /app/data/

# Create an output directory
RUN mkdir /app/output

# Run the PySpark application when the container starts
CMD ["python3", "app.py"]