# Use the official Python 3.12 slim image
FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script into the container
COPY main.py .

# Run the script when the container launches
CMD ["python", "main.py"]